# Site settings
title: JavaRoot
email: ing.edgarlira.g@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Programacion en java con diversos frameworks
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: edgarlira_ico
github_username:  javaroot

# Build settings
markdown: kramdown
highlighter: pygments
